### PR TITLE
Feature/install alb controller

### PR DESCRIPTION
**Pull request by FChataigner**
[ch44703]

run the howto of https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

notes on usage:
- put the `alb.ingress.kubernetes.io/scheme` -> `internet-facing` annotation on the ingress otherwise it's created internal
- you may need to kill -HUP the nginx pid to get it to work, because the ingress gives a hostname and it's usually not resolvable right away on the machine (so the nginx conf update with the brand new hostname fails)

### CODE REVIEW

**Review by hrjn — COMMENTED** [review]
Similarly to what was discussed on Slack:
* the macro requires elevated privileges (power to create IAM policies), are we OK with that or should we remove the policy creation step and document it so that it can be handled outside of DSS ?
* maybe explicitly warn users that it's not compatible with private clusters ?

Other than that, it works :) Successfully tested on a dummy DSS webapp (creation + deletion macros), by exposing it with the "ingress" mode and adding the following annotations: 
- `kubernetes.io/ingress.class: alb`
- `alb.ingress.kubernetes.io/scheme: internet-facing`

**Comment by FChataigner** [comment]
added a checkbox to explicitely request the policy creation, and some more help text. The list of permissions needed to run the macro remains long, though

Screenshot 2020-10-12 at 15 46 49

**Review by hrjn — APPROVED** [review]
All good 🙂 
I'll review the nginx-ingress dans la foulée and merge them with the proper versioning. Thx @FChataigner !

**Comment by apichery** [comment]
@hrjn Did you get a chance to review the nginx-ingress stuff?

**Comment by hrjn** [comment]
> @hrjn Did you get a chance to review the nginx-ingress stuff?

@apichery [I did](https://github.com/dataiku/dss-plugin-eks-clusters/pull/1#discussion_r511051800) 🙂 We could actually merge the ALB PR now and keep the nginx-ingress improvements for a later release.

**Pull request merged**
