### PR TITLE
Install GPU NVIDIA Drivers Macro EKS

### PR DESCRIPTION
**Pull request by xaaaaav**
Simple macro to install NVIDIA drivers to enable GPU EKS clusters. Can create or delete the daemonset using the macro.

### CODE REVIEW

**Comment by hrjn** [comment]
@xaaaaav there is a tiny (and completely unrelated) improvement that you could add, by including the latest plugin icon (see https://github.com/dataiku/dss-plugin-eks-clusters/issues/3). The issue has been pending for quite some time so it would be great to address it in one of the currently active PRs 🙂

**Comment by xaaaaav** [comment]
Done 🙂

**Comment by hrjn** [comment]
Thanks! I'll do a more thorough review later this week.

**Comment by hrjn** [comment]
@xaaaaav I'm putting this on hold so that I can merge the ALB PR that also contains some utilities to run kubectl in a cleaner way. 

Once it's done I'll ping you so that you can merge master in your GPU branch and refactor it using the new built-in utilities.

**Review by hrjn — CHANGES_REQUESTED** [review]
@xaaaaav would it be possible to enforce the GPU feature directly at the nodegroup creation level instead of a standalone macro? For an example, you can look at what's being done with the [GKE plugin](https://github.com/dataiku/dss-plugin-gke-clusters/blob/master/python-lib/dku_google/clusters.py).

**Comment by hrjn** [comment]
@xaaaaav any news on this? 🙂

**Comment by xaaaaav** [comment]
I actually think this is not needed anymore @hrjn. Looks like the latest versions of eksctl install the NVIDIA Kubernetes device drivers automatically just based on which instance type is being selected. https://eksctl.io/usage/gpu-support/. What do you think?

**Comment by hrjn** [comment]
We still need to account for:
* older versions of eksctl that are still in use
* the scenario where you create a cluster without GPU nodes and you add GPU-based nodegroup(s) afterwards

I'd say we keep moving forward with this implementation and make sure it's "robust" enough by maximising compatibility with existing setups. The recent eksctl additions will help, but they are not solving the whole problem.

**Comment by xaaaaav** [comment]
Makes total sense! I have something working now and just verifying that all the different test cases that I have work:

- Advanced YAML
  - version of eksctl >= 0.32.0
    - GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
    - non-GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
  - version of eksctl < 0.32.0
    - GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
    - non-GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
- Plugin Presets
  - version of eksctl >= 0.32.0
    - GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
    - non-GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
  - version of eksctl < 0.32.0
    - GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro
    - non-GPU-enabled cluster creation
      - add GPU nodegroup using macro
      - add non-GPU nodegroup using macro

Let me know if I missed any cases.

**Comment by xaaaaav** [comment]
Sorry, to be clear, the macro that is being called in those test cases is the "Add Nodegroup" macro. The install drivers macro has been removed and is going directly in the request as originally requested.

**Comment by xaaaaav** [comment]
I have more tests to do but the latest commits should give a sense of what I have been doing to match the request of putting it with the nodegroup.

**Comment by xaaaaav** [comment]
I have finished my testing, and the results prompt a question for me. When using eksctl >= 0.32.0, it will install the NVIDIA Device plugin, but it does not apply any labels/nodeSelectors. This means that non-GPU nodes can have the daemonset running on there, whether that be the nodes created with the cluster or nodes added later using the "Add Nodegroup" macro.

I have written the current changes such that for eksctl < 0.32.0, it labels the GPU nodes and applies the device plugin with a nodeSelector so that the daemonset only runs on nodes with GPUs.

@hrjn thoughts? I think it makes sense to only have the daemonset on GPU-enabled nodes. If so, need to do a few more tweaks to disable the automatic installation of the drivers by eksctl and handle it through the nodegroup request.

**Comment by hrjn** [comment]
I think it's simpler to leave the daemonset as it is, it's not like the generated pods would consume a lot of resources 🙂

**Comment by xaaaaav** [comment]
Would you prefer that I simplify for eksctl < 0.32.0 and remove the node labeling and just apply the daemonset?

**Comment by hrjn** [comment]
Yes, sounds good !

**Comment by xaaaaav** [comment]
Okay, this is all cleaned up and should be ready for review now.

**Review by hrjn — APPROVED** [review]
Verified on 8.0.5, looking good. Thx!

**Pull request merged**
